-- MySQL Script generated by MySQL Workbench
-- Mon Feb 11 23:52:23 2019
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `ece1779a1` ;

-- -----------------------------------------------------
-- Schema ece1779a1
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `ece1779a1` DEFAULT CHARACTER SET utf8 ;
USE `ece1779a1` ;

-- -----------------------------------------------------
-- Table `ece1779a1`.`user`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ece1779a1`.`user` ;

CREATE TABLE IF NOT EXISTS `ece1779a1`.`user` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `username` VARCHAR(45) NOT NULL,
  `password` VARCHAR(145) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ece1779a1`.`images`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ece1779a1`.`images` ;

CREATE TABLE IF NOT EXISTS `ece1779a1`.`images` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `filepath` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ece1779a1`.`user_has_images`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ece1779a1`.`user_has_images` ;

CREATE TABLE IF NOT EXISTS `ece1779a1`.`user_has_images` (
  `user_id` INT NOT NULL,
  `image_name` VARCHAR(100) NOT NULL,
  `user_id1` INT NULL,
  `images_id` INT NULL,
  PRIMARY KEY (`user_id`, `image_name`),
  INDEX `fk_user_has_images_user_idx` (`user_id1` ASC),
  INDEX `fk_user_has_images_images1_idx` (`images_id` ASC),
  CONSTRAINT `fk_user_has_images_user`
    FOREIGN KEY (`user_id1`)
    REFERENCES `ece1779a1`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_user_has_images_images1`
    FOREIGN KEY (`images_id`)
    REFERENCES `ece1779a1`.`images` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


CREATE USER 'ece1779a1' IDENTIFIED BY 'secret';
commit;

GRANT ALL ON ece1779a1.* TO 'ece1779a1';

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
